Bootstrap: docker
From: centos:7.6.1810

%help
    Here's where help options for running this singularity should appear.
    something like:
    singularity exec spades.simg spades.py ...

%labels
    MAINTAINER Curtis Kapsak
    SINGULARITY-IMAGE-VERSION 1.0.0
    SOFTWARE-VERSION 3.13.0

%environment
    PATH=${PATH}:/SPAdes-3.13.0-Linux/bin
    export PATH

%post
    yum -y update
    yum -y install wget python
    wget http://cab.spbu.ru/files/release3.13.0/SPAdes-3.13.0-Linux.tar.gz
    tar -xzf SPAdes-3.13.0-Linux.tar.gz
    rm -r SPAdes-3.13.0-Linux.tar.gz
    mkdir /data

%runscript
    echo "This runscript just shows SPAdes help options"
    spades.py --help
